spring:
  application:
    name: clean-architecture-order-application
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    hibernate:
      ddl-auto: validate
  flyway: #flyway automatically uses the datasource from the application to connect to the DB
    enabled: true # enables flyway database migration
    baseline-on-migrate: true # creates a baseline version of the schema if it doesn't exist

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    redis:
      enabled: false

application:
  product:
    types: FINISHED_GOOD, RAW_MATERIAL